[theme]
primaryColor = "#4CAF50"  # Green for buttons, etc.
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F0F5"  # Light grey for panels
textColor = "#000000"  # Black text
font = "sans serif"
